import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Plus, Trash2, Send, Download, FileText } from 'lucide-react';
import { useSales } from '@/contexts/SalesContext';
import { useToast } from '@/components/ui/use-toast';
import { CurrencyDisplay } from '@/components/ui/CurrencyDisplay';
import { ProductSearch } from '@/components/ui/product-search';
import { formatDate } from '@/lib/utils'; // Assuming this exists or I'll use inline
import { Product } from '@/services/products.service';

interface PrelevementFormProps {
    clients: any[]; // Replace with specific type if available (UIContact)
    products: Product[];
}

interface PrelevementItem {
    id: string;
    productId: string;
    description: string;
    quantity: number;
    unitPrice: number;
    total: number;
}

export const PrelevementForm: React.FC<PrelevementFormProps> = ({ clients, products }) => {
    const { t } = useTranslation();
    const { createPrelevement } = useSales();
    const { toast } = useToast();

    const [formClient, setFormClient] = useState<string>('');
    const [formDate, setFormDate] = useState<string>(new Date().toISOString().split('T')[0]);
    const [formNote, setFormNote] = useState<string>('');
    const [items, setItems] = useState<PrelevementItem[]>([
        { id: '1', productId: '', description: '', quantity: 1, unitPrice: 0, total: 0 }
    ]);
    const [isSubmitting, setIsSubmitting] = useState(false);

    // Calculate totals
    const subtotal = items.reduce((sum, item) => sum + item.total, 0);
    const total = subtotal; // No tax for now as per schema

    const updateItem = (id: string, field: keyof PrelevementItem, value: any) => {
        setItems(items.map(item => {
            if (item.id === id) {
                const updatedItem = { ...item, [field]: value };
                // Recalculate total for this item
                if (field === 'quantity' || field === 'unitPrice') {
                    updatedItem.total = updatedItem.quantity * updatedItem.unitPrice;
                }
                return updatedItem;
            }
            return item;
        }));
    };

    const addItem = () => {
        const newId = (Math.max(...items.map(i => parseInt(i.id))) + 1).toString();
        setItems([...items, { id: newId, productId: '', description: '', quantity: 1, unitPrice: 0, total: 0 }]);
    };

    const removeItem = (id: string) => {
        if (items.length > 1) {
            setItems(items.filter(i => i.id !== id));
        }
    };

    const handleProductSelect = (itemId: string, product: Product) => {
        updateItem(itemId, 'productId', product.id);
        updateItem(itemId, 'description', product.name);
        updateItem(itemId, 'unitPrice', product.price);
        // Force recalculate total
        setItems(currentItems => currentItems.map(item => {
            if (item.id === itemId) {
                return {
                    ...item,
                    productId: product.id,
                    description: product.name,
                    unitPrice: product.price,
                    total: item.quantity * product.price
                };
            }
            return item;
        }));
    };

    const handleSubmit = async () => {
        if (!formClient) {
            toast({ title: 'Validation Error', description: t('documents.selectClient'), variant: 'destructive' });
            return;
        }

        if (items.length === 0) {
            toast({ title: 'Validation Error', description: 'At least one item is required', variant: 'destructive' });
            return;
        }

        setIsSubmitting(true);
        try {
            await createPrelevement({
                client: formClient, // SalesContext will resolve this to clientData or ID
                clientData: clients.find(c => c.id === formClient),
                documentId: '', // Auto-generated by backend
                date: formDate,
                note: formNote,
                items: items.map(item => ({
                    id: item.id,
                    productId: item.productId,
                    description: item.description,
                    quantity: item.quantity,
                    unitPrice: item.unitPrice,
                    total: item.total
                })),
                total: total,
                status: 'draft',
            });

            // Reset form
            setItems([{ id: '1', productId: '', description: '', quantity: 1, unitPrice: 0, total: 0 }]);
            setFormClient('');
            setFormDate(new Date().toISOString().split('T')[0]);
            setFormNote('');

            // Note: Success toast is handled by mutation onError/onSuccess in Context usually, 
            // but we can add secondary confirmation if needed.
        } catch (error) {
            console.error(error);
            // Error handled by context
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="space-y-6 animate-fade-in">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2 space-y-6">
                    {/* Client Information */}
                    <div className="card-elevated p-6">
                        <h3 className="font-heading font-semibold text-foreground mb-4">{t('documents.clientInformation')}</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label>{t('documents.selectClient')}</Label>
                                <Select value={formClient} onValueChange={setFormClient}>
                                    <SelectTrigger>
                                        <SelectValue placeholder={t('documents.chooseClient')} />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {clients.map((client) => (
                                            <SelectItem key={client.id} value={client.id}>
                                                {client.company || client.name}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>
                            <div className="space-y-2">
                                <Label>Date du prélèvement</Label>
                                <Input type="date" value={formDate} onChange={(e) => setFormDate(e.target.value)} />
                            </div>
                            <div className="space-y-2">
                                <Label>Numéro de prélèvement</Label>
                                <Input placeholder={t('common.autoGenerated')} disabled />
                            </div>
                        </div>
                    </div>

                    {/* Articles Table */}
                    <div className="card-elevated p-6">
                        <div className="flex items-center justify-between mb-4">
                            <h3 className="font-heading font-semibold text-foreground">{t('documents.lineItems')}</h3>
                            <Button variant="outline" size="sm" onClick={addItem} className="gap-2">
                                <Plus className="w-4 h-4" />
                                {t('documents.addItem')}
                            </Button>
                        </div>
                        <div className="space-y-4">
                            {items.map((item) => (
                                <div key={item.id} className="p-4 border border-border rounded-lg space-y-4 bg-card">
                                    <div className="grid grid-cols-12 gap-4">
                                        <div className="col-span-12 md:col-span-5">
                                            <Label className="text-xs font-medium mb-1.5 block">Product (Optional)</Label>
                                            <ProductSearch
                                                products={products as any}
                                                value={item.productId}
                                                onSelect={(product) => handleProductSelect(item.id, product as any)}
                                                placeholder="Search product..."
                                            />
                                        </div>
                                        <div className="col-span-12 md:col-span-7">
                                            <Label className="text-xs font-medium mb-1.5 block">Description</Label>
                                            <Input
                                                placeholder="Description"
                                                value={item.description}
                                                onChange={(e) => updateItem(item.id, 'description', e.target.value)}
                                                className="w-full"
                                            />
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-12 gap-4 items-end">
                                        <div className="col-span-4 md:col-span-2">
                                            <Label className="text-xs font-medium mb-1.5 block">Quantity</Label>
                                            <Input
                                                type="number"
                                                min="1"
                                                value={item.quantity}
                                                onChange={(e) => updateItem(item.id, 'quantity', parseInt(e.target.value) || 0)}
                                                className="w-full"
                                            />
                                        </div>
                                        <div className="col-span-4 md:col-span-4">
                                            <Label className="text-xs font-medium mb-1.5 block">Unit Price (MAD)</Label>
                                            <Input
                                                type="number"
                                                min="0"
                                                step="0.01"
                                                value={item.unitPrice}
                                                onChange={(e) => updateItem(item.id, 'unitPrice', parseFloat(e.target.value) || 0)}
                                                className="w-full"
                                            />
                                        </div>
                                        <div className="col-span-4 md:col-span-4">
                                            <Label className="text-xs font-medium mb-1.5 block">Total (MAD)</Label>
                                            <Input value={item.total.toFixed(2)} disabled className="w-full font-medium" />
                                        </div>
                                        <div className="col-span-12 md:col-span-2 flex justify-end">
                                            <Button
                                                variant="ghost"
                                                size="icon"
                                                className="text-destructive hover:text-destructive hover:bg-destructive/10 h-10 w-10"
                                                onClick={() => removeItem(item.id)}
                                                disabled={items.length === 1}
                                                title="Remove item"
                                            >
                                                <Trash2 className="w-4 h-4" />
                                            </Button>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Note Section */}
                    <div className="card-elevated p-6">
                        <div className="space-y-2">
                            <Label>{t('documents.noteOptional')}</Label>
                            <Textarea
                                placeholder={t('documents.addNotes')}
                                value={formNote}
                                onChange={(e) => setFormNote(e.target.value)}
                                rows={3}
                                className="resize-none"
                            />
                        </div>
                    </div>
                </div>

                {/* Summary Sidebar */}
                <div className="space-y-6">
                    <div className="card-elevated p-6 sticky top-6">
                        <div className="flex items-center gap-2 mb-4">
                            <FileText className="w-5 h-5 text-primary" />
                            <h3 className="font-heading font-semibold text-foreground text-lg sm:text-base leading-tight">Résumé du prélèvement</h3>
                        </div>
                        <div className="space-y-3 overflow-visible">
                            <div className="flex justify-between py-3 text-lg gap-4 overflow-visible">
                                <span className="font-semibold text-foreground flex-shrink-0">Total</span>
                                <span className="font-heading font-bold text-primary break-words overflow-visible whitespace-normal text-right min-w-0">
                                    <CurrencyDisplay amount={total} />
                                </span>
                            </div>
                        </div>
                        <div className="mt-6 space-y-2">
                            <Button className="w-full gap-2 btn-primary-gradient" onClick={handleSubmit} disabled={isSubmitting}>
                                <Send className="w-4 h-4" />
                                {isSubmitting ? 'Creating...' : 'Create & Send Prélèvement'}
                            </Button>
                            <Button variant="outline" className="w-full gap-2" disabled>
                                <Download className="w-4 h-4" />
                                Download PDF
                            </Button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
